services:
  fetch:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MAX_QUOTES_PER_RUN: ${MAX_QUOTES_PER_RUN:-1}
      OFFLINE_MODE: ${OFFLINE_MODE:-false}
      DRY_RUN: ${DRY_RUN:-false}
    command: ["node", "scripts/fetch_quotes.mjs"]

  preview:
    image: nginx:alpine
    ports:
      - "4173:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped

